apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
    - git:
        repoURL: https://github.com/MarkRamm-harness/applicationset.git
        revision: master
        files:
        - path: "examples/git-generator-files-discovery/cluster-config/**/config.json"
  template:
    metadata:
      name: '{{cluster.name}}-guestbook'
    spec:
      project: aef2786b
      source:
        repoURL: https://github.com/MarkRamm-harness/applicationset.git
        targetRevision: master
        path: "examples/git-generator-files-discovery/apps/guestbook"
        kustomize:
          namePrefix: '{{cluster.name}}-'
      destination:
        server: https://kubernetes.default.svc
        #server: '{{cluster.address}}'
        namespace: default
